title:              Tania Nasrollahi
email:              tanian101@gmail.com
description:        A page about Tania Nasrollahi
author:             Tania Nasrollahi
baseurl:            "/tanianasrollahi2"
url:                "https://woof84.github.io"

# Social Profiles
twitter_username:   tniavv
github_username:
facebook_username:
instagram_username: tniav
linkedin_username:  tania-nasrollahi-057aa9190

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
